/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { Check, ArrowRight } from 'lucide-react';

export default function Success() {
  const REDIRECT_URL = 'https://jackie-jeans.vercel.app/';
  const [secondsRemaining, setSecondsRemaining] = useState(3);

  useEffect(() => {
    // Decrement countdown timer every second
    const interval = setInterval(() => {
      setSecondsRemaining((prev) => {
        if (prev <= 1) {
          clearInterval(interval);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    // Redirect after 3 seconds
    const timeout = setTimeout(() => {
      window.location.href = REDIRECT_URL;
    }, 3000);

    return () => {
      clearInterval(interval);
      clearTimeout(timeout);
    };
  }, []);

  const handleSkipRedirect = () => {
    window.location.href = REDIRECT_URL;
  };

  return (
    <div
      className="mx-auto flex max-w-md flex-col items-center justify-center px-4 py-16 text-center"
      style={{ minHeight: '70vh' }}
      id="success-page-container"
    >
      {/* Success Scale & Fade animation */}
      <motion.div
        initial={{ opacity: 0, scale: 0.8 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{
          type: 'spring',
          stiffness: 260,
          damping: 20,
          duration: 0.6,
        }}
        className="mb-8 flex h-24 w-24 items-center justify-center rounded-full bg-emerald-50 text-emerald-700 shadow-sm border border-emerald-200"
        id="success-animated-badge"
      >
        <Check className="h-12 w-12" />
      </motion.div>

      {/* Message Header */}
      <motion.h2
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="font-serif text-3xl font-bold tracking-tight text-editorial-text sm:text-4xl"
      >
        Fit Profile Created
      </motion.h2>

      <motion.p
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="mt-3 text-sm text-gray-500 font-sans font-light leading-relaxed max-w-xs"
      >
        Your bespoke fit profile has been successfully generated by Jackie AI.
      </motion.p>

      {/* Countdown Progress Slider */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="mt-12 w-full max-w-xs space-y-2 bg-warm-muted border border-editorial-border rounded-2xl p-4 text-center"
      >
        <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block">
          Redirecting in {secondsRemaining}s
        </span>
        <div className="relative h-1 w-full overflow-hidden rounded-full bg-editorial-border/60">
          <motion.div
            className="h-full rounded-full bg-emerald-600"
            initial={{ width: '100%' }}
            animate={{ width: '0%' }}
            transition={{ duration: 3, ease: 'linear' }}
          />
        </div>
      </motion.div>

      {/* Manual Immediate CTA Skip Button */}
      <motion.button
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6 }}
        onClick={handleSkipRedirect}
        className="mt-8 flex items-center justify-center gap-1.5 text-xs font-bold tracking-widest uppercase text-denim-700 bg-denim-50 hover:bg-denim-100/60 border border-editorial-border rounded-full px-5 py-3 shadow-sm transition-all cursor-pointer"
        style={{ minHeight: '44px' }}
        id="success-skip-redirect-btn"
      >
        <span>Redirect Immediately</span>
        <ArrowRight className="h-3.5 w-3.5" />
      </motion.button>
    </div>
  );
}
